const imagesTum = [
  { id: 1, src: './images/image1tum.jpg'},
  { id: 2, src: './images/image2tum.jpg'},
  { id: 3, src: './images/image3tum.jpg'},
  { id: 4, src: './images/image4tum.jpg'},
  { id: 5, src: './images/image5tum.jpg'},
  { id: 6, src: './images/image6tum.jpg'},
  { id: 7, src: './images/image7tum.jpg'},
  { id: 8, src: './images/image8tum.jpg'},
  { id: 9, src: './images/image9tum.jpg'},
  { id: 10, src: './images/image10tum.jpg'},
  { id: 11, src: './images/image11tum.jpg'},
  { id: 12, src: './images/image12tum.jpg'},
  { id: 13, src: './images/image13tum.jpg'},
  { id: 14, src: './images/image14tum.jpg'},
  { id: 15, src: './images/image15tum.jpg'},
  { id: 16, src: './images/image16tum.jpg'},
  { id: 17, src: './images/image17tum.jpg'},
  { id: 18, src: './images/image18tum.jpg'},
  { id: 19, src: './images/image19tum.jpg'},
  { id: 20, src: './images/image20tum.jpg'},
  { id: 21, src: './images/image21tum.jpg'},
  { id: 22, src: './images/image22tum.jpg'},
  { id: 23, src: './images/image23tum.jpg'},
  { id: 24, src: './images/image24tum.jpg'},
  { id: 25, src: './images/image25tum.jpg'},
  { id: 26, src: './images/image26tum.jpg'},
  { id: 27, src: './images/image27tum.jpg'},
  { id: 28, src: './images/image28tum.jpg'},
  { id: 29, src: './images/image29tum.jpg'},
  { id: 30, src: './images/image30tum.jpg'},
  { id: 31, src: './images/image31tum.jpg'},
  { id: 32, src: './images/image32tum.jpg'},
  { id: 33, src: './images/image33tum.jpg'},
  { id: 34, src: './images/image34tum.jpg'},
  { id: 35, src: './images/image35tum.jpg'},
];



export default imagesTum;